name = "desea-factura-webhooks"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Forzar HTTPS
[env.production]
routes = []

# Configuración de compatibilidad
compatibility_flags = []

# Variables de entorno (configurar después)
[vars]
# SHOPIFY_API_SECRET se configura como secret 